owncast:
  url: "my-very-owncast-server.live"
  port: 443
  access-key: "XYZ"

commands:
  - description: "Does ABC, pretty well to be honest"
    triggers:
      - "!abc"
      - "!a"
    actions:
      - chat_message:
          - "Gimme an A"
          - "Gimme a B"
          - "Gimme a C"
          - "ABC!"

timers:
  - alias: "ABC-timer"
    description: "Does ABC, but in a timely manner"
    actions:
      - chat_message:
          - "Gimme an A"
          - "Gimme a B"
          - "Gimme a C"
          - "ABC!"
      - system_message:
      - chat_action:
    interval: "15"
